# -*- coding: utf-8 -*-
# (c) Copyright 2021 Sensirion AG, Switzerland

##############################################################################
##############################################################################
#                 _____         _    _ _______ _____ ____  _   _
#                / ____|   /\  | |  | |__   __|_   _/ __ \| \ | |
#               | |       /  \ | |  | |  | |    | || |  | |  \| |
#               | |      / /\ \| |  | |  | |    | || |  | | . ` |
#               | |____ / ____ \ |__| |  | |   _| || |__| | |\  |
#                \_____/_/    \_\____/   |_|  |_____\____/|_| \_|
#
#     THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED MANUALLY!
#
# Generator:    sensirion-shdlc-interface-generator 0.8.1
# Product:      SFA3x
# Version:      0.1.0
#
##############################################################################
##############################################################################

# flake8: noqa

from __future__ import absolute_import, division, print_function
from sensirion_shdlc_driver.command import ShdlcCommand
from struct import pack, unpack

import logging
log = logging.getLogger(__name__)


class Sfa3xCmdDeviceResetBase(ShdlcCommand):
    """
    SHDLC command 0xD3: "Device Reset".
    """

    def __init__(self, *args, **kwargs):
        """
        Constructor.
        """
        super(Sfa3xCmdDeviceResetBase, self).__init__(
            0xD3, *args, **kwargs)


class Sfa3xCmdDeviceReset(Sfa3xCmdDeviceResetBase):
    """
    Device Reset Command

    Executes a reset on the device.

    .. note:: The device will reply before executing the reset.
    """

    def __init__(self):
        """
        Constructor.
        """
        super(Sfa3xCmdDeviceReset, self).__init__(
            data=[],
            max_response_time=0.2,
            post_processing_time=0.2,
            min_response_length=0,
            max_response_length=0
        )
